NLP

In [ ]:
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from collections import Counter
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("whatsapp_chat.csv")

In [3]:
df

Chat_ID Sender          Message            Timestamp       Talkative  \
0         1  Alice  <Media omitted>  2025-08-09 10:00:00       Talkative   
1         2  Alice  <Media omitted>  2025-08-13 12:29:00       Talkative   
2         3    Bob       good night  2025-08-12 14:02:00  Less Talkative   
3         4  Alice        beautiful  2025-08-01 11:34:00       Talkative   
4         5  Alice  <Media omitted>  2025-08-07 06:19:00       Talkative   
..      ...    ...              ...                  ...             ...   
95       96  Alice       good night  2025-08-13 06:28:00       Talkative   
96       97    Bob  <Media omitted>  2025-08-09 17:32:00  Less Talkative   
97       98    Bob        beautiful  2025-08-11 07:57:00  Less Talkative   
98       99    Bob             work  2025-08-05 10:56:00  Less Talkative   
99      100  Alice            noted  2025-08-11 11:47:00       Talkative   

   Most_Active_Day Most_Active_Time  Media_Count  Missed_Calls  Flirt_Label  
0         Saturday      10:00-11:00            1             0            0  
1        Wednesday      12:00-13:00            1             0            0  
2          Tuesday      14:00-15:00            0             0            0  
3           Friday      11:00-12:00            0             0            1  
4         Thursday        6:00-7:00            1             0            0  
..             ...              ...          ...           ...          ...  
95       Wednesday        6:00-7:00            0             0            0  
96        Saturday      17:00-18:00            1             0            0  
97          Monday        7:00-8:00            0             0            1  
98         Tuesday      10:00-11:00            0             0            0  
99          Monday      11:00-12:00            0             0            0  

[100 rows x 10 columns]

In [4]:
df = df.drop(columns=["Chat_ID"])

In [5]:
df

Sender          Message            Timestamp       Talkative  \
0   Alice  <Media omitted>  2025-08-09 10:00:00       Talkative   
1   Alice  <Media omitted>  2025-08-13 12:29:00       Talkative   
2     Bob       good night  2025-08-12 14:02:00  Less Talkative   
3   Alice        beautiful  2025-08-01 11:34:00       Talkative   
4   Alice  <Media omitted>  2025-08-07 06:19:00       Talkative   
..    ...              ...                  ...             ...   
95  Alice       good night  2025-08-13 06:28:00       Talkative   
96    Bob  <Media omitted>  2025-08-09 17:32:00  Less Talkative   
97    Bob        beautiful  2025-08-11 07:57:00  Less Talkative   
98    Bob             work  2025-08-05 10:56:00  Less Talkative   
99  Alice            noted  2025-08-11 11:47:00       Talkative   

   Most_Active_Day Most_Active_Time  Media_Count  Missed_Calls  Flirt_Label  
0         Saturday      10:00-11:00            1             0            0  
1        Wednesday      12:00-13:00            1             0            0  
2          Tuesday      14:00-15:00            0             0            0  
3           Friday      11:00-12:00            0             0            1  
4         Thursday        6:00-7:00            1             0            0  
..             ...              ...          ...           ...          ...  
95       Wednesday        6:00-7:00            0             0            0  
96        Saturday      17:00-18:00            1             0            0  
97          Monday        7:00-8:00            0             0            1  
98         Tuesday      10:00-11:00            0             0            0  
99          Monday      11:00-12:00            0             0            0  

[100 rows x 9 columns]

In [6]:
y=df["Flirt_Label"]

In [7]:
dataset=df

In [8]:
X_train, X_test, y_train, y_test = train_test_split(dataset['Message'], y, test_size=0.33, random_state=53)

In [9]:
df.isnull().sum()

Sender              0
Message             0
Timestamp           0
Talkative           0
Most_Active_Day     0
Most_Active_Time    0
Media_Count         0
Missed_Calls        0
Flirt_Label         0
dtype: int64

In [10]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 108 stored elements and shape (67, 27)>
  Coords	Values
  (0, 3)	1
  (1, 11)	1
  (1, 18)	1
  (2, 7)	1
  (3, 11)	1
  (3, 18)	1
  (4, 22)	1
  (5, 13)	1
  (5, 24)	1
  (6, 26)	1
  (7, 11)	1
  (7, 18)	1
  (8, 2)	1
  (9, 13)	1
  (9, 24)	1
  (11, 11)	1
  (11, 18)	1
  (12, 6)	1
  (13, 13)	1
  (13, 24)	1
  (14, 9)	1
  (14, 15)	1
  (15, 19)	1
  (16, 23)	1
  (17, 0)	1
  :	:
  (51, 24)	1
  (52, 11)	1
  (52, 18)	1
  (53, 13)	1
  (53, 25)	1
  (54, 13)	1
  (54, 24)	1
  (55, 4)	1
  (56, 13)	1
  (56, 24)	1
  (57, 12)	1
  (58, 8)	1
  (59, 1)	1
  (60, 13)	1
  (60, 25)	1
  (61, 21)	1
  (62, 22)	1
  (63, 11)	1
  (63, 18)	1
  (64, 13)	1
  (64, 25)	1
  (65, 9)	1
  (65, 15)	1
  (66, 11)	1
  (66, 18)	1


In [11]:
len(count_vectorizer.get_feature_names_out())

27

In [12]:
print(count_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
clf = MultinomialNB()

clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

cm = metrics.confusion_matrix(y_test, pred, labels=['0', '1'])

accuracy:   1.000


In [14]:
from sklearn.metrics import classification_report

report=classification_report(y_test, pred)

In [15]:
dataset["Message"][0]

'<Media omitted>'

In [16]:
count_train[[0]]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1 stored elements and shape (1, 27)>

In [17]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)

In [18]:
X_train.iloc[0]

'dear'

# Countervectorizer

In [19]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.linear_model import LogisticRegression, SGDClassifier, PassiveAggressiveClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

def countervector():
    # Load dataset
    df = pd.read_csv('whatsapp_chat.csv')
    dataset = df.drop(columns=["Unnamed: 0"], errors="ignore")   
    X = dataset['Message']
    y = dataset['Flirt_Label']
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=53)

    # CountVectorizer
    count_vectorizer = CountVectorizer(stop_words='english')
    count_train = count_vectorizer.fit_transform(X_train)
    count_test = count_vectorizer.transform(X_test)

    # Define classifiers
    classifiers = {
        "MultinomialNB": MultinomialNB(),
        "BernoulliNB": BernoulliNB(),
        "LogisticRegression": LogisticRegression(max_iter=2000),
        "LinearSVC": LinearSVC(),
        "SGDClassifier": SGDClassifier(),
        "PassiveAggressive": PassiveAggressiveClassifier(),
        "RandomForest": RandomForestClassifier()
    }

    # Store results
    results = []

    # Train & evaluate each classifier
    for name, clf in classifiers.items():
        clf.fit(count_train, y_train)
        pred = clf.predict(count_test)
        acc = metrics.accuracy_score(y_test, pred)
        results.append((name, acc))
        print(f"{name} Accuracy: {acc:.4f}")

    # Sort results by accuracy
    results.sort(key=lambda x: x[1], reverse=True)

    print("\n=== Accuracy Ranking ===")
    for name, acc in results:
        print(f"{name}: {acc:.4f}")

# Run the function
countervector()


MultinomialNB Accuracy: 1.0000
BernoulliNB Accuracy: 0.7273
LogisticRegression Accuracy: 0.7273
LinearSVC Accuracy: 1.0000
SGDClassifier Accuracy: 1.0000
PassiveAggressive Accuracy: 1.0000


C:\Anaconda3\envs\dineshML\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


RandomForest Accuracy: 1.0000

=== Accuracy Ranking ===
MultinomialNB: 1.0000
LinearSVC: 1.0000
SGDClassifier: 1.0000
PassiveAggressive: 1.0000
RandomForest: 1.0000
BernoulliNB: 0.7273
LogisticRegression: 0.7273


# TfidfVectorizer

In [20]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.linear_model import LogisticRegression, SGDClassifier, PassiveAggressiveClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

def tfidfvectorizer():
    # Load dataset
    df = pd.read_csv('whatsapp_chat.csv')
    dataset = df.drop(columns=["Unnamed: 0"], errors="ignore")   
    X = dataset['Message']
    y = dataset['Flirt_Label']
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=53)

    # TfidfVectorizer
    tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
    tfidf_train = tfidf_vectorizer.fit_transform(X_train)
    tfidf_test = tfidf_vectorizer.transform(X_test)

    # Define classifiers
    classifiers = {
        "MultinomialNB": MultinomialNB(),
        "BernoulliNB": BernoulliNB(),
        "LogisticRegression": LogisticRegression(max_iter=2000),
        "LinearSVC": LinearSVC(),
        "SGDClassifier": SGDClassifier(),
        "PassiveAggressive": PassiveAggressiveClassifier(),
        "RandomForest": RandomForestClassifier()
    }

    # Store results
    results = []

    # Train & evaluate each classifier
    for name, clf in classifiers.items():
        clf.fit(tfidf_train, y_train)
        pred = clf.predict(tfidf_test)
        acc = metrics.accuracy_score(y_test, pred)
        results.append((name, acc))
        print(f"{name} Accuracy: {acc:.4f}")

    # Sort results by accuracy
    results.sort(key=lambda x: x[1], reverse=True)

    print("\n=== Accuracy Ranking ===")
    for name, acc in results:
        print(f"{name}: {acc:.4f}")

# Run the function
tfidfvectorizer()


MultinomialNB Accuracy: 0.7273
BernoulliNB Accuracy: 0.7273
LogisticRegression Accuracy: 0.6970
LinearSVC Accuracy: 1.0000
SGDClassifier Accuracy: 1.0000
PassiveAggressive Accuracy: 1.0000


C:\Anaconda3\envs\dineshML\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


RandomForest Accuracy: 1.0000

=== Accuracy Ranking ===
LinearSVC: 1.0000
SGDClassifier: 1.0000
PassiveAggressive: 1.0000
RandomForest: 1.0000
MultinomialNB: 0.7273
BernoulliNB: 0.7273
LogisticRegression: 0.6970


# Final Model

In [21]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

def final_model():
    # Load dataset
    df = pd.read_csv('whatsapp_chat.csv')
    dataset = df.drop(columns=["Unnamed: 0"], errors="ignore")
    X = dataset['Message']
    y = dataset['Flirt_Label']
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.33, random_state=53
    )

    # CountVectorizer
    count_vectorizer = CountVectorizer(stop_words='english')
    count_train = count_vectorizer.fit_transform(X_train)
    count_test = count_vectorizer.transform(X_test)

   
    clf = MultinomialNB()
    clf.fit(count_train, y_train)

    # Evaluate
    pred = clf.predict(count_test)
    acc = metrics.accuracy_score(y_test, pred)
    print(f"Final Model (MultinomialNB) Accuracy: {acc:.4f}")

    # === Example prediction on new messages ===
    new_messages = [
        "Hey you look amazing today ",
        "Meeting at 5 PM in office",
        "Can we go out for dinner?"
    ]
    new_transformed = count_vectorizer.transform(new_messages)
    predictions = clf.predict(new_transformed)

    for msg, label in zip(new_messages, predictions):
        print(f"Message: '{msg}' --> Prediction: {label}")

# Run final model
final_model()


Final Model (MultinomialNB) Accuracy: 1.0000
Message: 'Hey you look amazing today ' --> Prediction: 1
Message: 'Meeting at 5 PM in office' --> Prediction: 0
Message: 'Can we go out for dinner?' --> Prediction: 0


# Check flirt messages

In [22]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB


df = pd.read_csv("whatsapp_chat.csv")

# Ensure Message is string
X = df["Message"].astype(str)       # Input features (messages)
y = df["Flirt_Label"]               # Target (0 = Not Flirt, 1 = Flirt)


vectorizer = CountVectorizer(stop_words="english")
X_vec = vectorizer.fit_transform(X)


model = MultinomialNB()
model.fit(X_vec, y)

df["Flirt_Prediction"] = model.predict(X_vec)   # Predicted label

# Prediction probabilities
probs = model.predict_proba(X_vec)
df["Not_Flirt_Prob"] = probs[:, 0]
df["Flirt_Prob"] = probs[:, 1]


print(df.head(10))   # Show first 10 rows
df.to_csv("flirt_predictions.csv", index=False)
print("\n Results saved to flirt_predictions.csv")


   Chat_ID Sender            Message            Timestamp       Talkative  \
0        1  Alice    <Media omitted>  2025-08-09 10:00:00       Talkative   
1        2  Alice    <Media omitted>  2025-08-13 12:29:00       Talkative   
2        3    Bob         good night  2025-08-12 14:02:00  Less Talkative   
3        4  Alice          beautiful  2025-08-01 11:34:00       Talkative   
4        5  Alice    <Media omitted>  2025-08-07 06:19:00       Talkative   
5        6  Alice  Missed video call  2025-08-15 17:48:00       Talkative   
6        7  Alice    <Media omitted>  2025-08-14 17:33:00       Talkative   
7        8  Alice               dear  2025-08-11 06:46:00       Talkative   
8        9    Bob  Missed video call  2025-08-03 18:40:00  Less Talkative   
9       10  Alice  Missed video call  2025-08-15 14:34:00       Talkative   

  Most_Active_Day Most_Active_Time  Media_Count  Missed_Calls  Flirt_Label  \
0        Saturday      10:00-11:00            1             0            0

In [23]:
data=pd.read_csv("flirt_predictions.csv")
data

Chat_ID Sender          Message            Timestamp       Talkative  \
0         1  Alice  <Media omitted>  2025-08-09 10:00:00       Talkative   
1         2  Alice  <Media omitted>  2025-08-13 12:29:00       Talkative   
2         3    Bob       good night  2025-08-12 14:02:00  Less Talkative   
3         4  Alice        beautiful  2025-08-01 11:34:00       Talkative   
4         5  Alice  <Media omitted>  2025-08-07 06:19:00       Talkative   
..      ...    ...              ...                  ...             ...   
95       96  Alice       good night  2025-08-13 06:28:00       Talkative   
96       97    Bob  <Media omitted>  2025-08-09 17:32:00  Less Talkative   
97       98    Bob        beautiful  2025-08-11 07:57:00  Less Talkative   
98       99    Bob             work  2025-08-05 10:56:00  Less Talkative   
99      100  Alice            noted  2025-08-11 11:47:00       Talkative   

   Most_Active_Day Most_Active_Time  Media_Count  Missed_Calls  Flirt_Label  \
0         Saturday      10:00-11:00            1             0            0   
1        Wednesday      12:00-13:00            1             0            0   
2          Tuesday      14:00-15:00            0             0            0   
3           Friday      11:00-12:00            0             0            1   
4         Thursday        6:00-7:00            1             0            0   
..             ...              ...          ...           ...          ...   
95       Wednesday        6:00-7:00            0             0            0   
96        Saturday      17:00-18:00            1             0            0   
97          Monday        7:00-8:00            0             0            1   
98         Tuesday      10:00-11:00            0             0            0   
99          Monday      11:00-12:00            0             0            0   

    Flirt_Prediction  Not_Flirt_Prob  Flirt_Prob  
0                  0        0.997315    0.002685  
1                  0        0.997315    0.002685  
2                  0        0.891941    0.108059  
3                  1        0.204436    0.795564  
4                  0        0.997315    0.002685  
..               ...             ...         ...  
95                 0        0.891941    0.108059  
96                 0        0.997315    0.002685  
97                 1        0.204436    0.795564  
98                 0        0.794007    0.205993  
99                 0        0.794007    0.205993  

[100 rows x 13 columns]

# Find talkative / less talkative

In [24]:

msg_count = df["Sender"].value_counts()
most_talkative = msg_count.idxmax()
least_talkative = msg_count.idxmin()

print("Most Talkative:", most_talkative, "(", msg_count.max(), "messages )")
print("Less Talkative:", least_talkative, "(", msg_count.min(), "messages )")


Most Talkative: Alice ( 54 messages )
Less Talkative: Bob ( 46 messages )


# Find most active day & time

In [25]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")

# Get Day and Hour
df["Day"] = df["Timestamp"].dt.day_name()
df["Hour"] = df["Timestamp"].dt.hour

print("Most Active Day:", df["Day"].value_counts().idxmax())
print("Most Active Hour:", df["Hour"].value_counts().idxmax())


Most Active Day: Thursday
Most Active Hour: 20


# Count media messages per person

In [26]:
media_msgs = df[df["Message"].str.contains("Media omitted", case=False, na=False)]
print("\nMedia Messages Sent By Each Person:")
print(media_msgs["Sender"].value_counts())


Media Messages Sent By Each Person:
Sender
Alice    15
Bob      14
Name: count, dtype: int64


# Count missed calls

In [27]:
missed_calls = df[df["Message"].str.contains("missed call", case=False, na=False)]
print("\nMissed Calls By Each Person:")
print(missed_calls["Sender"].value_counts())


Missed Calls By Each Person:
Series([], Name: count, dtype: int64)
